### ISSUE TITLE
Test suite fails 35 tests on a clean checkout; no public CI to catch it

### ISSUE THREAD

**Issue by aquilu** [google-antigravity/antigravity-sdk-python#156]
## Summary

`pytest` on a clean checkout of `main` fails 35 tests. I reproduced this in a pristine `git archive main` extraction, outside my working tree, so it is not a local artefact.

```
35 failed, 722 passed, 6 warnings, 5 subtests passed in 4.28s
```

This is not a report about flaky tests — the failures are deterministic and fall into three groups, none of which indicate a defect in the SDK itself. The point is that an outside contributor cannot get a green baseline, so there is no way to tell whether a change breaks anything.

## Repro

```sh
git clone https://github.com/google-antigravity/antigravity-sdk-python
cd antigravity-sdk-python
python -m pip install -e ".[dev]" pytest-cov
python -m grpc_tools.protoc -I. --python_out=. google/antigravity/proto/*
touch google/antigravity/proto/__init__.py
python -m pytest -q
```

(The `protoc` line is the one from `.kokoro/presubmit.sh`; it works fine.)

## Group 1 — 23 tests: no `localharness` binary in a source checkout

`create_strategy()` resolves the binary eagerly, and `README.md` states the binary ships only in the PyPI wheels, so any test that constructs a strategy raises:

```
RuntimeError: Could not find default localharness binary.
```

Three test classes already anticipate this and patch the resolver in `setUp`:

```python
mock.patch(
    "google.antigravity.connections.local.local_connection._get_default_binary_path",
    return_value="/fake/binary",
)
```

`LocalAgentConfigTest`, `LocalConnectionSubagentsTest`, `LiteRTConnectionTest` and `LocalOpenAIConnectionTest` do not, and those are the 23 failures.

## Group 2 — 2 tests: export debris

Filed separately as #155, since it likely belongs to whoever owns the export rather than to the SDK.

## Group 3 — the rest: absl flags under pytest

The tests are written for `absltest` but `.kokoro/presubmit.sh` runs them under `pytest`, which never parses absl's flags, so `absltest`'s temporary-directory helpers fail. A root `conftest.py` with:

```python
from absl import flags
if not flags.FLAGS.is_parsed():
    flags.FLAGS(["pytest"])
```

is enough. One class (`AgentConfigTest`) also needs `IsolatedAsyncioTestCase` rather than `TestCase` for its async cases.

## Why this persists

`.kokoro/` is Google-internal, so there is no public signal — `git log` shows no CI configuration in this repository, and nothing runs on pull requests or pushes. The suite can regress in the export without anyone outside noticing.

## Happy to help

I have a branch that takes this to `756 passed` and adds a GitHub Actions matrix (3.10–3.13, plus a wheel-import smoke test on Linux/macOS/Windows), with each commit verified independently. `CONTRIBUTING.md` says external contributions are not being accepted, so I am not opening a PR — but if the patches are useful to you I am glad to share them in whatever form suits, or you are welcome to take the diagnosis above and implement it yourselves.

## Environment

`main` at `6f6e99a`, Python 3.13.14, macOS/arm64, `websockets` 16.1.1, `pydantic` 2.13.4.

**Comment by aquilu** [comment]
One more, found by actually running a matrix rather than reasoning about it.

**The suite cannot run on Python 3.10, which `pyproject.toml` declares as the minimum.**

`LocalConnectionSubagentsTest.setUp` (`local_connection_test.py:4307` on `main`) calls `TestCase.enterContext`, added in Python 3.11:

```
AttributeError: 'LocalConnectionSubagentsTest' object has no attribute 'enterContext'
9 failed, 747 passed
```

3.11, 3.12 and 3.13 pass. The 3.10-compatible spelling is equivalent:

```python
tmp_dir = tempfile.TemporaryDirectory()
self.addCleanup(tmp_dir.cleanup)
self.temp_dir = tmp_dir.name
```

This is only a test-side incompatibility — it says nothing about whether the SDK itself works on 3.10 — but it does mean the declared floor of the supported range has no test coverage at all, and cannot have had any since `enterContext` was introduced.

I mention it because it is a clean example of what the missing CI costs: every check I ran locally was on 3.13, where the call exists, so nothing short of a matrix could surface it. With the matrix in place the full set is green: `quality`, `tests` on 3.10–3.13, and a wheel-import smoke test on Linux, macOS and Windows.

**Comment by NTaylorMullen** [comment]
Done in latest release (v0.1.10)
